#!/usr/bin/env python
"""Run Toy Squares TeLoGraF dataset generation and policy training.

This assumes a full Toy Squares HDF5 already exists, typically generated by
telograf_toy_squares/generate_toy_squares_data.sh. It then runs:

  1. STL/data diagnostics.
  2. TeLoGraF-compatible event-only dataset mining.
  3. TeLoGraF flow policy training.
"""

from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
import time
from pathlib import Path


POLICY_CONFIGS = {
    "h16": {
        "horizon": 16,
        "default_epochs": 200,
        "default_batch_size": 256,
        "default_eval_samples": 512,
        "description": "clean single-reach primitive policy",
    },
    "h64": {
        "horizon": 64,
        "default_epochs": 200,
        "default_batch_size": 256,
        "default_eval_samples": 512,
        "description": "fixed-horizon single-reach policy matching TeLoGraF small-domain horizon",
    },
    "h128": {
        "horizon": 128,
        "default_epochs": 200,
        "default_batch_size": 128,
        "default_eval_samples": 256,
        "description": "padded paper-budget single-reach policy",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset",
        type=Path,
        default=Path("outputs/telograf/toy_squares/raw/full_10k/data.hdf5"),
        help="Full Toy Squares HDF5 with train/valid masks.",
    )
    parser.add_argument("--policy", choices=sorted(POLICY_CONFIGS), required=True)
    parser.add_argument("--output-root", type=Path, default=Path("outputs/telograf/toy_squares"))
    parser.add_argument("--name", type=str, default=None, help="Suffix for dataset/run names.")
    parser.add_argument("--pre-event-steps", type=int, default=16)
    parser.add_argument("--radius", type=float, default=0.2)
    parser.add_argument("--chain-base", type=str, default="blue,yellow,green,red")
    parser.add_argument("--max-chain-horizon", type=int, default=5)
    parser.add_argument("--epochs", type=int, default=None)
    parser.add_argument("--batch-size", type=int, default=None)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--n-timesteps", type=int, default=100)
    parser.add_argument("--dim", type=int, default=64)
    parser.add_argument("--dim-mults", type=int, nargs="+", default=[1, 2, 4, 8])
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--eval-samples", type=int, default=None)
    parser.add_argument("--save-every", type=int, default=50)
    parser.add_argument("--seed", type=int, default=11)
    parser.add_argument("--debug", action="store_true", help="Small, fast debug run over a subset.")
    parser.add_argument("--max-demos", type=int, default=None, help="Optional cap for diagnostics/mining.")
    parser.add_argument("--max-per-spec", type=int, default=5000)
    parser.add_argument("--skip-diagnostics", action="store_true")
    parser.add_argument("--skip-training", action="store_true")
    parser.add_argument("--allow-local-fallback", action="store_true", help="Allow non-TeLoGraF local fallback backend.")
    parser.add_argument("--cpu", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def run_command(cmd: list[str], dry_run: bool = False) -> None:
    printable = " ".join(shlex.quote(part) for part in cmd)
    print(f"\n$ {printable}", flush=True)
    if dry_run:
        return
    subprocess.run(cmd, check=True)


def main() -> None:
    args = parse_args()
    cfg = POLICY_CONFIGS[args.policy]
    horizon = int(cfg["horizon"])
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    suffix = args.name or f"{args.policy}_{timestamp}"

    epochs = int(args.epochs if args.epochs is not None else cfg["default_epochs"])
    batch_size = int(args.batch_size if args.batch_size is not None else cfg["default_batch_size"])
    eval_samples = int(args.eval_samples if args.eval_samples is not None else cfg["default_eval_samples"])
    max_demos = args.max_demos
    max_per_spec = int(args.max_per_spec)
    if args.debug:
        epochs = min(epochs, 1)
        batch_size = min(batch_size, 32)
        eval_samples = min(eval_samples, 32)
        max_demos = max_demos or 128
        max_per_spec = min(max_per_spec, 128)
        args.dim = min(args.dim, 32)
        args.num_workers = 0

    diagnostics_root = args.output_root / "diagnostics"
    datasets_root = args.output_root / "datasets"
    runs_root = args.output_root / "runs"
    dataset_name = f"toy_squares_reach_{suffix}"
    run_name = f"toy_squares_reach_{suffix}_telograf"
    data_npz = datasets_root / dataset_name / "data.npz"

    if not args.dataset.exists() and not args.dry_run:
        raise FileNotFoundError(
            f"Toy Squares dataset not found: {args.dataset}. "
            "Generate it first with telograf_toy_squares/generate_toy_squares_data.sh."
        )

    print(f"policy={args.policy} horizon={horizon} ({cfg['description']})", flush=True)
    print(f"dataset={args.dataset}", flush=True)
    print(f"output_root={args.output_root}", flush=True)

    if not args.skip_diagnostics:
        diag_cmd = [
            sys.executable,
            "-m",
            "telograf_toy_squares.diagnose_toy_squares_data",
            "--dataset",
            str(args.dataset),
            "--output-root",
            str(diagnostics_root),
            "--horizon",
            str(horizon),
            "--horizon-candidates",
            "16",
            "32",
            "64",
            "96",
            "128",
            "--pre-event-steps",
            str(args.pre_event_steps),
            "--radius",
            str(args.radius),
            "--chain-base",
            str(args.chain_base),
            "--max-chain-horizon",
            str(args.max_chain_horizon),
        ]
        if max_demos is not None:
            diag_cmd.extend(["--max-demos", str(max_demos)])
        run_command(diag_cmd, dry_run=args.dry_run)

    make_cmd = [
        sys.executable,
        "-m",
        "telograf_toy_squares.make_telograf_dataset",
        "--dataset",
        str(args.dataset),
        "--output-root",
        str(datasets_root),
        "--name",
        dataset_name,
        "--horizon",
        str(horizon),
        "--pre-event-steps",
        str(args.pre_event_steps),
        "--radius",
        str(args.radius),
        "--chain-base",
        str(args.chain_base),
        "--max-chain-horizon",
        str(args.max_chain_horizon),
        "--max-per-spec",
        str(max_per_spec),
        "--eventual-only",
    ]
    if max_demos is not None:
        make_cmd.extend(["--max-demos", str(max_demos)])
    run_command(make_cmd, dry_run=args.dry_run)

    if args.skip_training:
        print(f"\nDataset ready at {data_npz}", flush=True)
        return

    train_cmd = [
        sys.executable,
        "-m",
        "telograf_toy_squares.train_telograf_toy_squares",
        "--data",
        str(data_npz),
        "--output-root",
        str(runs_root),
        "--name",
        run_name,
        "--epochs",
        str(epochs),
        "--batch-size",
        str(batch_size),
        "--lr",
        str(args.lr),
        "--n-timesteps",
        str(args.n_timesteps),
        "--dim",
        str(args.dim),
        "--dim-mults",
        *[str(item) for item in args.dim_mults],
        "--num-workers",
        str(args.num_workers),
        "--eval-samples",
        str(eval_samples),
        "--save-every",
        str(args.save_every),
        "--seed",
        str(args.seed),
    ]
    if args.cpu:
        train_cmd.append("--cpu")
    if not args.allow_local_fallback:
        train_cmd.append("--require-telograf-backend")
    run_command(train_cmd, dry_run=args.dry_run)

    print(f"\nPipeline complete. Dataset: {data_npz}", flush=True)
    print(f"Run dir: {runs_root / run_name}", flush=True)


if __name__ == "__main__":
    main()
