#!/bin/sh
#SBATCH -J diffusion_policy
#SBATCH -A rpaleja
#SBATCH -p a100-40gb
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-node=1
#SBATCH --mem=32G
#SBATCH --qos=normal
#SBATCH -t 24:00:00
#SBATCH -o slurm-%j.out

module load conda
#conda activate /scratch/gilbreth/zoellner/conda/envs/guided_diffusion
conda activate guided_diffusion

export MUJOCO_GL=egl
export EGL_DEVICE_ID=0
export CUDA_VISIBLE_DEVICES=0
unset DISPLAY

CKPT_PATH=/scratch/gilbreth/zoellner/diffusion_runs/can_mh_lowdim/20260209180642/models/model_epoch_2000.pth
echo "Starting diffusion policy training via SLURM"
cd ~/src/guided-diffusion
start_time=$(date +%s)
python -u predicion/precompute_rzz.py --input data/can/mh/low_dim_v15.hdf5 --output data/guidance/rzz_mh_can.hdf5 --ckpt_path ${CKPT_PATH}
end_time=$(date +%s)
elapsed=$((end_time - start_time))
echo "Finished training? elapsed_seconds=${elapsed}"
