#!/bin/sh
#SBATCH -J rollout_baseDP
#SBATCH -A rpaleja
#SBATCH -p a100-40gb
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-node=1
#SBATCH --mem=32G
#SBATCH --qos=normal
#SBATCH -t 1:00:00
#SBATCH -o slurm-%j.out

module load conda
#conda activate /scratch/gilbreth/zoellner/conda/envs/guided_diffusion
conda activate guided_diffusion

export MUJOCO_GL=egl
export EGL_DEVICE_ID=0
export CUDA_VISIBLE_DEVICES=0
unset DISPLAY

CKPT_PATH=/scratch/gilbreth/zoellner/diffusion_runs/can_mh_lowdim/20260209180642/models/model_epoch_2000.pth
#CKPT_PATH=/scratch/gilbreth/zoellner/diffusion_runs/can_ph_lowdim/20260209201546/models/model_epoch_2000.pth
echo "Starting base rollout training via SLURM"
cd ~/src/guided-diffusion
start_time=$(date +%s)
python -u experiments/rollout_base_policy.py \
  --n_rollouts 50 \
  --output_path /scratch/gilbreth/zoellner/diffusion_rollouts/can_rollouts \
  --ckpt_path ${CKPT_PATH} \
  --n_step_rollout_video 1 \
  --horizon 300 \
  --name policy_diversity_mh_h300_pos \
  --fix_init_state y 
end_time=$(date +%s)
elapsed=$((end_time - start_time))
echo "Finished base rollout? elapsed_seconds=${elapsed}"
